### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by linuxgurugamer** [allista/AutoLoadGame#1]
Can you create a simple UI which would allow the player to select which  game to autoload, instead of having to edit a file?

Shouldn't be difficult, just display a list of directories of the saves, and then, when one is selected, display a list of all the .sfs files

**Comment by allista** [comment]
Well, I'll try to when I have some time. I made this mod purely to help testers and devs who sometimes have to load the same save tens, even hundreds of times a day while bughunting. But since it has attracted some attention, I'll put some work into usability.

**Comment by linuxgurugamer** [comment]
No need for this anymore, Malah has one also

**Comment by allista** [comment]
Sorry, has one what also?

**Comment by linuxgurugamer** [comment]
Malah has a mod which does what I requested, so no need for you to do this

**Comment by allista** [comment]
May I have a link, please? If there's a mod that does all this with a UI, I'll just drop this one.

**Comment by linuxgurugamer** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/85834-122-malahs-quick-mods-20161209/
Look for QuickStart

**Comment by allista** [comment]
A pity that I didn't know about it when I started to made this one.
Seems I will have to drop the development...

**Comment by linuxgurugamer** [comment]
No worries.  Think of it as a learning process.
Thanks for doing it, it was helpful to me for a while
