### ISSUE TITLE
Not working in 1.1.3?

### ISSUE THREAD

**Issue by Jiraiyah** [allista/AutoLoadGame#3]
Hi
I tried your mod in 1.1.3 but it's not working, am i missing something?

**Comment by allista** [comment]
It would seem so, because it works on my side alright. Have you created/edited the config file according to the docs?

**Comment by Jiraiyah** [comment]
yup, take a look : 
http://prntscr.com/co5xdu
game = Sand
save = persistent
http://prntscr.com/co5xkv
although i didn't start any flights but shouldn't it load this saved game?
keep in mind this save is sand box though

**Comment by allista** [comment]
All looks good. And the game should indeed be loading into KSC. Could you share the log then?

**Comment by Jiraiyah** [comment]
ksp log : 
http://pastebin.com/9TGRiZTe
and i can't use paste bin for output log, it's too big, where can i post it?

**Comment by allista** [comment]
I usually post it zipped using Dropbox or Google Drive.

**Comment by Jiraiyah** [comment]
here you go
https://www.dropbox.com/s/r9a9l91ktxxcbmb/output_log.zip?dl=0

**Comment by allista** [comment]
Thanks a lot!
The problem is my AT_Utils library that is missing from your installation:

```
AddonLoader: Instantiating addon 'AutoLoadGame' from assembly 'AutoLoadGame'
FileNotFoundException: Could not load file or assembly '000_AT_Utils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```

I use this library for all my projects, but since its use in AutoLoadGame is minimal I'll stop referencing it. No need for such a simple plugin to have any dependencies.

I'll soon post the new release without this dependency.
