### ISSUE TITLE
Problem with tweak scale mod

### ISSUE THREAD

**Issue by Jiraiyah** [allista/AutoLoadGame#4]
Hi
I found that tweak scale mod was not working and I narrowed down the problem and found that when your mod is outside of game data folder, tweak scale behaves, as soon as i add your mod back, it stops working, is this a known issue or new?
here is the link for original problem in tweak scale forum post : 
http://forum.kerbalspaceprogram.com/index.php?/topic/99956-wip-tweakscale-development-thread/&do=findComment&comment=2783637
and here is the output log just in case it would help : 
https://www.dropbox.com/s/r9a9l91ktxxcbmb/output_log.zip?dl=0

**Comment by allista** [comment]
I don't know what's going on there, but you have A LOT of exceptions telling that Assembly Loader cannot load many different mods. And none of them point to the ALG; nor can it affect assembly loading process in any way.
So I would guess there's something wrong with the installation, versions, etc.

**Comment by Jiraiyah** [comment]
No, I tried tweak scale with a new instance of ksp, it worked, added your mod and it didn't work, for some reason, it looks like tweak scale does something in the loading screen or the game instance launch screen that your mod is bypassing it? maybe talk to developer of tweak scale about this? or if you need, i can use that pure instance to get a cleaner output log for you

**Comment by allista** [comment]
Yea, cleaner output log would be great.
I'll look into TS code tomorrow. 
ALG does the same thing KSP does when you load the game manually. It just does this as soon as the main screen have been loaded. So in principle it may interfere with something that starts at the same time and tries to do some work...

**Comment by Jiraiyah** [comment]
OK, take a look at this image, this is the folder, as you see i just added a simple module manager patch to tweak the module for tweak scale on orbital survey
http://prntscr.com/cp320d
now here is the output file
https://www.dropbox.com/s/lrvnnxjuw5sb7hd/output_log.zip?dl=0
the result again is the same as what you can see in screen shots in the forum posts i sent the link to you

**Comment by pellinor0** [comment]
Not sure what fails here but it should fail more gracefully. I'll also have a look. 

```
Module TweakScale threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
  at TweakScale.ScaleExponents.CreateExponentsForModule (.ConfigNode node, System.Collections.Generic.Dictionary`2 parent) [0x00000] in <filename unknown>:0 
  at TweakScale.ScaleType..ctor (.ConfigNode partConfig) [0x00000] in <filename unknown>:0 
  at TweakScale.TweakScale.Setup () [0x00000] in <filename unknown>:0 
  at TweakScale.TweakScale.OnStart (StartState state) [0x00000] in <filename unknown>:0 
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 

(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
Module TweakScale threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
  at TweakScale.ScaleExponents.CreateExponentsForModule (.ConfigNode node, System.Collections.Generic.Dictionary`2 parent) [0x00000] in <filename unknown>:0 
  at TweakScale.ScaleType..ctor (.ConfigNode partConfig) [0x00000] in <filename unknown>:0 
  at TweakScale.TweakScale.Setup () [0x00000] in <filename unknown>:0 
  at TweakScale.TweakScale.OnStart (StartState state) [0x00000] in <filename unknown>:0 
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 
```

 @Jiraiyah do you need your custom patch to make it fail? If it is the one from the TweakScale thread, I just noticed that
`%SCALETYPE {...}`
looks suspicious to me. I only know this syntax in the form 
`%SOMETHING[name] {...}`
which either creates or edits a node of type SOMETHING with the given name. Since you are creating a new scaleType you probably want to leave out the %.

**Comment by Jiraiyah** [comment]
not really, even without the patch it fails

**Comment by Jiraiyah** [comment]
the only reason i had that % in front of scale type was that i was not sure if it would work without it or not, i am not that familiar with patching with module manager myself. but even without my patch it is still broken

**Comment by allista** [comment]
This may be fixed in 996caf4b04069233b05ded417f15503656ce5cb1.
I had a similar problem with TAC LifeSupport that was fixed by that commit.

**Comment by Jiraiyah** [comment]
still didn't check it, but interesting, Awake() would be called as soon as the scripts are being loaded to the game, yah, that may have fixed it ;) will give it a try and tell you the result later

**Comment by Jiraiyah** [comment]
confirmed the fix on tweak scale, thanks sir
