### ISSUE TITLE
suggest: KSP-AVC

### ISSUE THREAD

**Issue by skalou** [allista/AutoLoadGame#5]
hi Allista, great to see you developping an other great mod! ;)
however for AutoLoadGame there isn't a forum to discuss about it, and no KSP-AVC file, i you like i can submit theses files as a pull request.

**Comment by allista** [comment]
Well, I never thought this mod would get any attention, as I made it just to ease the testing while developing other mods. I'm still not sure if a forum thread is needed, but KSP-AVC is simple enough to add, so why not?
A pull request would be great, thank you!

*_and some time later I'll add automatic generation of the file, as in all other mods._

**Comment by skalou** [comment]
i use it too for (trying to) modding ;)
i pushed the request, hop it's OK.

**Comment by allista** [comment]
Merged and using. Thanks!!!
