### ISSUE TITLE
Interference with EVE

### ISSUE THREAD

**Issue by voicey99** [allista/AutoLoadGame#9]
With ALG installed, EVE seems to be unable to initialise, leading to EVE effects being absent until the save is reloaded from the main menu, rendering ALG moot. Possibly loading the save before EVE can start its effects? Tested on a clean install with only EVE and ALG (after much swapping out of mods).

[Log](https://drive.google.com/open?id=1QxUZXUwFUGfShyPJA5n6YKx2ARn_VMKF)

[Output log](https://drive.google.com/open?id=1dGeT14c-55uPZ2o119iz6PyF-ct8xcW3)

**Comment by allista** [comment]
This should probably be fixed in the new version:
https://spacedock.info/mod/832/AutoLoadGame

**Comment by mlheur** [comment]
I can confirm with KSP 1.3.1 with EVE 1.2.2.1;  and KSP 1.4.3 with EVE 1.4.2.2 ; both with ALG 1.0.7 work fine.

**Comment by allista** [comment]
Glad to hear!
